name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      uses: npm install
    - name: Deploy master change to github page
      run: npm run deploy
